chore: Replace short SHAs with full SHAs
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `actions/cache@b820478`, the provided ref `b820478` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `b8204782bbb5f872091ecc5eb9cb7d004e35b1fa` instead.
Unable to resolve action `actions/checkout@722adc6`, the provided ref `722adc6` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `722adc63f1aa60a57ec37892e133b1d319cae598` instead.
Unable to resolve action `actions/upload-artifact@3446296`, the provided ref `3446296` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `3446296876d12d4e3a0f3145a3c87e67bf0a16b5` instead.
Unable to resolve action `crazy-max/ghaction-docker-buildx@552c9de`, the provided ref `552c9de` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `552c9de485482d9bbaa6fa035ee55e518e1e3cb9` instead.
Retrying in 13.787 seconds
Failed to resolve action download info. Error: Unable to resolve action `actions/cache@b820478`, the provided ref `b820478` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `b8204782bbb5f872091ecc5eb9cb7d004e35b1fa` instead.
Unable to resolve action `actions/checkout@722adc6`, the provided ref `722adc6` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `722adc63f1aa60a57ec37892e133b1d319cae598` instead.
Unable to resolve action `actions/upload-artifact@3446296`, the provided ref `3446296` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `3446296876d12d4e3a0f3145a3c87e67bf0a16b5` instead.
Unable to resolve action `crazy-max/ghaction-docker-buildx@552c9de`, the provided ref `552c9de` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `552c9de485482d9bbaa6fa035ee55e518e1e3cb9` instead.
Retrying in 13.668 seconds
Error: Unable to resolve action `actions/cache@b820478`, the provided ref `b820478` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `b8204782bbb5f872091ecc5eb9cb7d004e35b1fa` instead.
Unable to resolve action `actions/checkout@722adc6`, the provided ref `722adc6` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `722adc63f1aa60a57ec37892e133b1d319cae598` instead.
Unable to resolve action `actions/upload-artifact@3446296`, the provided ref `3446296` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `3446296876d12d4e3a0f3145a3c87e67bf0a16b5` instead.
Unable to resolve action `crazy-max/ghaction-docker-buildx@552c9de`, the provided ref `552c9de` is the shortened version of a commit SHA, which is not supported. Please use the full commit SHA `552c9de485482d9bbaa6fa035ee55e518e1e3cb9` instead.

Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>